"""auto-vote

Revision ID: b542166f0200
Revises: c64fccdae412
Create Date: 2025-05-25 23:36:00.847352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b542166f0200'
down_revision: Union[str, None] = 'c64fccdae412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table(
            "votes",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("post_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(["post_id"], ["Posts.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("user_id", "post_id")
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("votes")
    # ### commands auto generated by Alembic - please adjust! ###
    